### PR TITLE
[IN PROGRESS] Squash migrations to neaten things up.

### PR DESCRIPTION
**Pull request by nein09**

### CODE REVIEW

**Comment by eldang** [comment]
NB: the only commit I'm actually reviewing here is https://github.com/missoula-ready/disaster-preparedness/commit/dffef51bbdf9f02fd28e9b45e7c94ba96c9041f1 - for the migrations themselves I'm trusting that Django did something sensible.

**Comment by nein09** [comment]
Eeeeek that wasn't ready to go- that's why I put 'in progress on it'

*mel (phone)

**Comment by eldang** [comment]
Oh. Um... I'll see if I can back it out. I'm used to PRs not being made
until they're actually a request, so I misunderstood your intent.

**Comment by eldang** [comment]
OK, reverted.  I don't know how to reopen this PR though - maybe you have to make another?  Sorry about this.

**Comment by nein09** [comment]
Sorry for the misunderstanding! It's no big deal for me to reopen it- I open them so other folks can easily see what I'm up to. It's a piece of culture I picked up on my team at substantial.

*mel (phone)

**Pull request merged**
