### PR TITLE
[REVIEW] Display Intensity icons

### PR DESCRIPTION
**Pull request by nein09**
Display intensity icons if there is an image field in the snugget (generating the icons is forthcoming).

I also made the requested color changes to the icons.

### CODE REVIEW

**Comment by eldang** [comment]
This looks good to me.

**Comment by eldang** [comment]
BTW, if we put the generated SVG inline, I _think_ we can set the segment colours using CSS, which seems more convenient for future users to customise colours with.

**Comment by nein09** [comment]
That'd be super boss and I will try doing that with the generated one - if it works, I'll backport it to these.

**Comment by eldang** [comment]
I am not 100% sure about this, but I think we can only apply CSS to SVG elements that are inline in the HTML page, not SVG files that are embedded like images.

**Comment by nein09** [comment]
Oh, that would make sense.

**Pull request merged**
