### PR TITLE
made import.py find .CPG files

### PR DESCRIPTION
**Pull request by eldang**

### CODE REVIEW

**Comment by nein09** [comment]
Is this likely to happen with other file extensions? If so, you might want to create a helper method instead and use it everywhere you have to find a file. Something like

```
def get_file_contents(inputDir, stem, extension)
          file = os.path.join(inputDir, stem+extension)
         # if file is not found, try upper case extension in case we're on a case sensitive file system
         if not os.path.exists(file):
           file = os.path.join(inputDir, stem+extension.upper())

     with open(file, 'r') as f:
       return f.read()
```

**Comment by eldang** [comment]
Hrm.  This is kind of a unique case.  Now that you mention it, there is one other line where it checks for the existence of a file, but that's different enough that I think it makes sense to handle separately.  One more commit incoming, to do that.

**Comment by nein09** [comment]
⛵️

**Comment by eldang** [comment]
OK, I think this is worth merging now.  There are no other places where this script looks for a file by name.  It does check for the existence of /reprojected and /simplified directories, but since it makes those itself it can count on consistent lowercase.

**Comment by eldang** [comment]
and... jinx :D

**Comment by eldang** [comment]
I'll port this to both the deployments now.

**Pull request merged**
